version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "8889:3306"
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bron_db
      # # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER_NAME: root
      DB_PASSWORD: root
      DB_NAME: bron_db
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  mysql_data:


  